spring:
  datasource:
    url: jdbc:mysql://localhost:13306/shopplus?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Seoul&allowPublicKeyRetrieval=true&useSSL=false
    username: shopplus
    password: shopplus-pass
  data:
    redis:
      host: localhost
      port: 6379
