spring:
  datasource:
    url: jdbc:mysql://mysql:3306/shopplus?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Seoul&allowPublicKeyRetrieval=true&useSSL=false
    username: shopplus
    password: shopplus-pass
  data:
    redis:
      host: redis
      port: 6379
